import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

export class ObsidianVault {
  constructor(vaultPath) {
    this.vaultPath = vaultPath;
    this.ensureDir('');
  }

  ensureDir(subdir) {
    const full = join(this.vaultPath, subdir);
    if (!existsSync(full)) mkdirSync(full, { recursive: true });
  }

  writeSourceIndex(source) {
    const content = `# ${source.name}

type:: ${source.type}
created:: ${source.created_at}
last_fetch:: ${source.last_fetch_at || 'never'}

## Overview

This sources contains data from **${source.name}**.
`;
    this.writeFile(`${source.name.replace(/[^a-zA-Z0-9_-]/g, '_')}/index.md`, content);
  }

  writeTreeNode(node, sourceName, level) {
    const subdir = `${sourceName.replace(/[^a-zA-Z0-9_-]/g, '_')}/${level}s`;
    this.ensureDir(subdir);

    const date = node.start_time ? node.start_time.slice(0, 10) : 'unknown';
    const filename = `${date}-${node.title.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 80)}.md`;
    const filepath = join(subdir, filename);

    const content = `# ${node.title}

level:: ${node.level}
items:: ${node.item_count}
tokens:: ${node.token_count}
created:: ${node.created_at}
start:: ${node.start_time || ''}
end:: ${node.end_time || ''}

${node.summary || '(no summary)'}

---
*Auto-generated by MemCore | ${new Date().toISOString().slice(0, 10)}*
`;

    writeFileSync(join(this.vaultPath, filepath), content, 'utf-8');
    return filepath;
  }

  writeRootSummary(sourceName, rootNodes) {
    const subdir = `${sourceName.replace(/[^a-zA-Z0-9_-]/g, '_')}`;
    this.ensureDir(subdir);

    let content = `# ${sourceName} - Knowledge Base\n\n`;
    content += `updated:: ${new Date().toISOString()}\n\n`;

    for (const node of rootNodes) {
      content += `## ${node.title}\n\n`;
      content += node.summary || '(empty)\n\n';
      content += `---\n\n`;
    }

    this.writeFile(`${subdir}/knowledge-base.md`, content);
  }

  writeFile(relativePath, content) {
    const fullPath = join(this.vaultPath, relativePath);
    const dir = fullPath.slice(0, fullPath.lastIndexOf('\\'));
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, content, 'utf-8');
  }

  writeMappingFile() {
    const content = `# MemCore Obsidian Vault
This vault is auto-generated by MemCore.

## Structure
- \`<source>/index.md\` — Source overview
- \`<source>/hours/<date>-<title>.md\` — Hourly summaries
- \`<source>/days/<date>-<title>.md\` — Daily summaries
- \`<source>/weeks/<date>-<title>.md\` — Weekly summaries
- \`<source>/months/<date>-<title>.md\` — Monthly summaries
- \`<source>/knowledge-base.md\` — Compiled knowledge

## Format
Each note uses Obsidian-compatible frontmatter tags.
`;
    this.writeFile('_memcore_mapping.md', content);
  }
}
